### ISSUE TITLE
bug count and reporter should include plotly.js and plotly.py etc...

### ISSUE THREAD

**Issue by bpostlethwaite** [plotly/plotbot#29]

**Comment by perigee** [comment]
@bpostlethwaite  if i didn't make mistake, the code lying here https://github.com/plotly/plotbot/blob/master/bugger/bugger.go#L31 needs to be changed.

**Comment by bpostlethwaite** [comment]
yep that is correct ;) We just need a loop. You think you will get to this issue this week? Not a giant priority but it will help me keep the bug momentum up with our team.
