### ISSUE TITLE
Plotbot to report back the deployed HEAD commit id

### ISSUE THREAD

**Issue by monfera** [plotly/plotbot#46]
It's important to know, across time, when exactly new things were deployed on `prod` and what branch and commit id (branch alone isn't good because that may evolve further, ie. the commit is a function of of time of deploy, or history gets rewritten; commit id alone would work but it's useful to know the branch).

Reasons:
- given a time (eg. now, or a specific time in the past), be certain what commit id is deployed on `prod` to facilitate bug triaging
- be able to respond to client complaints or legal inquiries (audit trail)
- see who deployed

Discussing the weekend things, @etpinard had the thought that as a 1st step, plotbot could be made to report the actually deploying HEAD commit. It'd make things searchable on the `#streambed` channel (ie. it needs some constant, searchable prefix text). 

Since plotbot is asked to deploy an implied or specified branch, the commit id is enough, and I also think it needs to be a commit id because other commit-ish things are time-varying (branches routinely evolve, they can be - non-routinely - reset; tags can be relocated with `-f`).

Maybe there's also some tool that generates an audit trail from deployments but it'd already be useful. 

Btw. we're bouncing around ideas for us to be able to tell which `plotly.js` commit is being used on `prod` (and/or in a `streambed` commit-ish), such as 1) always referring to a commit id if `streambed` points to the github repo rather than an `npm` version; 2) maybe bump the version number in `plotly.js` _immediately after_ `npm publish` so there's no ambiguity; 3) also, perhaps put the commit id in the `plotly.js` version, or some other property on the `Plotly` object, ideally automatically, eg. `Plotly.commitId` would always return a commit hash.

**Comment by scjody** [comment]
We do have complete logs of every deploy in #deploy. This is archived by Slack forever, and is searchable and exportable.

You can determine what commit is deployed to prod right now using `@plotbot What's in the pipe?`.

Showing the commit ID of what's currently being deployed is a good idea. The best place to do that is in one of the task files under https://github.com/plotly/streambed/tree/master/deployment/roles (in streambed), probably https://github.com/plotly/streambed/blob/master/deployment/roles/streambed/tasks/main.yml . Anything printed from a task file will end up in #deploy.

No plotbot changes are needed to support this so I'm closing this issue. Please reopen if I'm misunderstanding your suggestion.

**Comment by monfera** [comment]
In `#deploy` it says `[deployer] Using latest revision of cf-extracted branch` so there commit id isn't recoverable in retrospect, and the above proposal was about historical stuff rather than what's about to be deployed. _Deleted: What you suggest sounds like a good way, I'm not sure what the cons/pros of using `#deploy` are, it's a very voluminous log but doesn't show all info eg. who initiated the deploy (though can be found manually in `streambed` if needed)_

... hmm search doesn't seem to work there, eg. trying to grep for deploys, 
```
in: #deploy Using
```
or similar result this, maybe there's some other syntax

![image](https://user-images.githubusercontent.com/1548516/33849632-74840a38-deb1-11e7-8770-438fcac50a0f.png)

So emitting to `#deploy` doesn't seem useful for going back in history.

**Comment by scjody** [comment]
@monfera `in:#deploy “Using latest revision”` works for me to show the latest deploys.

As I said above, showing the commit ID of the current deploy is a good idea **but it can be done using the Ansible task files** in streambed, so no plotbot changes are needed to make that happen.

**Comment by monfera** [comment]
@scjody thanks, that search (with normal quotes too) don't work for me, not sure what's going on. You're more than right about the Ansible task point, but it's of little utility if we can't search. I'll circle back to why search doesn't work for me
